COMMENT = Library for Blu-Ray disc playback
VERSION = 1.4.0
REVISION = 0
CATEGORIES = libs
PKGNAME = libbluray
HOMEPAGE = https://www.videolan.org/developers/libbluray.html
ARCHIVE = libbluray-1.4.0.tar.xz
LINK = https://download.videolan.org/pub/videolan/libbluray/1.4.0/libbluray-1.4.0.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = libbluray-1.4.0
BUILD_OPTION = -Ddefault_library=shared \
	-Dlibxml2=disabled \
	-Dfreetype=disabled \
	-Djava9=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
