COMMENT = Modular status panel for X11 and Wayland, inspired by Polybar
VERSION = 1.9.0
REVISION = 0
CATEGORIES = xapps
PKGNAME = yambar
HOMEPAGE = https://codeberg.org/dnkl/yambar
ARCHIVE = 1.9.0.tar.gz
LINK = https://codeberg.org/dnkl/yambar/archive/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = yambar
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
