COMMENT = Wayland utils tools
VERSION = 1.3.0
REVISION = 0
CATEGORIES = tool
PKGNAME = wayland_utils
HOMEPAGE = https://wayland.freedesktop.org
ARCHIVE = wayland-utils-1.3.0.tar.xz
LINK = https://gitlab.freedesktop.org/wayland/wayland-utils/-/releases/1.3.0/downloads/wayland-utils-1.3.0.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = wayland-utils-1.3.0
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
