COMMENT = C++ bindings to Cairo vector graphics library
VERSION = 1.14.5
REVISION = 0
CATEGORIES = libs
PKGNAME = cairomm1.14
HOMEPAGE = https://www.cairographics.org
ARCHIVE = cairomm-1.14.5.tar.xz
LINK = https://www.cairographics.org/releases/cairomm-1.14.5.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = cairomm-1.14.5
BUILD_OPTION = -Dboost-shared=true -Dbuild-tests=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
