COMMENT = C++ wrappers for GTK+
VERSION = 3.24.10
REVISION = 0
CATEGORIES = libs
PKGNAME = gtkmm3
HOMEPAGE = https://www.gtkmm.org/
ARCHIVE = gtkmm-3.24.10.tar.xz
LINK = https://download.gnome.org/sources/gtkmm/3.24/gtkmm-3.24.10.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = gtkmm-3.24.10
BUILD_OPTION = -Dbuild-demos=false -Dbuild-tests=true

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
