COMMENT = X C-language Binding - X constants and keycodes
VERSION = 0.4.1
REVISION = 0
CATEGORIES = libs
PKGNAME = xcb_util_keysyms
HOMEPAGE = https://xcb.freedesktop.org/
ARCHIVE = xcb-util-keysyms-0.4.1.tar.xz
LINK = https://xcb.freedesktop.org/dist/xcb-util-keysyms-0.4.1.tar.xz
SRCCD = archive
BUILD = make
BUILDDIR = xcb-util-keysyms-0.4.1
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
