COMMENT = Asynchronous Name Service Library
VERSION = 0.8
REVISION = 0
CATEGORIES = libs
PKGNAME = libasyncns
HOMEPAGE = http://0pointer.de/lennart/projects/libasyncns/
ARCHIVE = libasyncns-0.8.tar.gz
LINK = https://dev.alpinelinux.org/archive/libasyncns-0.8.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = libasyncns-0.8
BUILD_OPTION =
AUTO_CONF = (cd ${BUILDDIR} && ./configure \
	--prefix=/usr \
	--sysconfdir=/etc \
	--libdir=/usr/lib)
MAKEOPT =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
