COMMENT = X C-language Binding - Convenience functions for XRender extension
VERSION = 0.3.10
REVISION = 0
CATEGORIES = libs
PKGNAME = xcb_util_renderutil
HOMEPAGE = https://xcb.freedesktop.org/
ARCHIVE = xcb-util-renderutil-0.3.10.tar.xz
LINK = https://xcb.freedesktop.org/dist/xcb-util-renderutil-0.3.10.tar.xz
SRCCD = archive
BUILD = make
BUILDDIR = xcb-util-renderutil-0.3.10
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
