COMMENT = View fonts on your system
VERSION = 49.0
REVISION = 0
CATEGORIES = font
PKGNAME = gnome_font_viewer
HOMEPAGE = https://gitlab.gnome.org/GNOME/gnome-font-viewer
ARCHIVE = gnome-font-viewer-49.0.tar.xz
LINK = https://download.gnome.org/sources/gnome-font-viewer/49/gnome-font-viewer-49.0.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = gnome-font-viewer-49.0
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
