COMMENT = Utility libraries for X C-language Binding
VERSION = 0.4.1
REVISION = 0
CATEGORIES = libs
PKGNAME = xcb_util
HOMEPAGE = https://xcb.freedesktop.org/
ARCHIVE = xcb-util-0.4.1.tar.xz
LINK = https://xorg.freedesktop.org/archive/individual/lib/xcb-util-0.4.1.tar.xz
SRCCD = archive
BUILD = make
BUILDDIR = xcb-util-0.4.1
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
