COMMENT = XKBD keymap compiler
VERSION = 1.5.0
REVISION = 0
CATEGORIES = xapps
PKGNAME = xkbcomp
HOMEPAGE = https://xorg.freedesktop.org
ARCHIVE = xkbcomp-1.5.0.tar.xz
LINK = https://www.x.org/releases/individual/app/xkbcomp-1.5.0.tar.xz
SRCCD = archive
BUILD = make
BUILDDIR = xkbcomp-1.5.0
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
