COMMENT = Command line screen capture util 
VERSION = 0.10.0
REVISION = 0
CATEGORIES = xapps
PKGNAME = scrot
HOMEPAGE = https://github.com/dreamer/scrot
ARCHIVE = scrot-${VERSION}.tar.gz
LINK = https://github.com/dreamer/scrot/archive/v${VERSION}/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = scrot-${VERSION}
BUILD_OPTION = --buildtype=release 

prepare:

post_build:

include /usr/share/mk/lfs.port.mk
