COMMENT = Efficient dynamic menu for Wayland
VERSION = 0.2.0
REVISION = 0
CATEGORIES = wayland
PKGNAME = wmenu
HOMEPAGE = https://codeberg.org/adnano/wmenu
ARCHIVE = 0.2.0.tar.gz
LINK = https://codeberg.org/adnano/wmenu/archive/0.2.0.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = wmenu
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
