COMMENT = Perfect hash function generator.
VERSION = 3.3
REVISION = 0
CATEGORIES = tool
PKGNAME = gperf
HOMEPAGE = https://www.gnu.org/software/gperf/
ARCHIVE = gperf-3.3.tar.gz
LINK = https://ftp.gnu.org/gnu/gperf/gperf-3.3.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = gperf-3.3
BUILD_OPTION =
AUTO_CONF = (cd ${BUILDDIR} && ./configure \
	--prefix=/usr \
	--sysconfdir=/etc \
	--libdir=/usr/lib \
	--build=x86_64-pc-linux-musl)
MAKEOPT =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
