COMMENT = A minimal status bar for Wayland compositors.
VERSION = 0.0.5
REVISION = 0
CATEGORIES = wayland
PKGNAME = ergo
HOMEPAGE = https://github.com/d4yr41n/ergo
ARCHIVE = ergo-0.0.5.tar.gz
LINK = https://github.com/pubfnmain/ergo/releases/download/0.0.5/ergo-0.0.5.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = ergo-0.0.5
MAKEOPT =
override PREFIX = $(PWD)/package/usr

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
