COMMENT = X keyboard configuration files
VERSION = 2.46
REVISION = 0
CATEGORIES = misc
PKGNAME = xkeyboard_config
HOMEPAGE = https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config
ARCHIVE = xkeyboard-config-xkeyboard-config-2.46.tar.gz
LINK = https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/archive/xkeyboard-config-2.46/xkeyboard-config-xkeyboard-config-2.46.tar.gz	
SRCCD = archive
BUILD = meson
BUILDDIR = xkeyboard-config-xkeyboard-config-2.46

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
