COMMENT = Multitouch Protocol Translation Library.
VERSION = 1.1.7
REVISION = 0
CATEGORIES = libs
PKGNAME = mtdev
HOMEPAGE = https://bitmath.org/code/mtdev/
ARCHIVE = mtdev-1.1.7.tar.bz2
LINK = https://bitmath.org/code/mtdev/mtdev-1.1.7.tar.bz2
SRCCD = archive
BUILD = make
BUILDDIR = mtdev-1.1.7
AUTO_CONF = (cd ${BUILDDIR} && ./configure \
	--prefix=/usr \
	--sysconfdir=/etc \
	--libdir=/usr/lib \
	--build=x86_64-pc-linux-musl)
MAKEOPT =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
