COMMENT = Utility to manage outputs of a Wayland compositor
VERSION = 0.5.0
REVISION = 0
CATEGORIES = wayland
PKGNAME = wlr_randr
HOMEPAGE = https://gitlab.freedesktop.org/emersion/wlr-randr
ARCHIVE = wlr-randr-v0.5.0.tar.gz
LINK = https://gitlab.freedesktop.org/emersion/wlr-randr/-/archive/v0.5.0/wlr-randr-v0.5.0.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = wlr-randr-v0.5.0
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
