COMMENT = X C-language Binding - helpers for ICCCM and EWMH
VERSION = 0.4.2
REVISION = 0
CATEGORIES = libs
PKGNAME = xcb_util_wm
HOMEPAGE = https://xcb.freedesktop.org/
ARCHIVE = xcb-util-wm-0.4.2.tar.xz
LINK = https://xcb.freedesktop.org/dist/xcb-util-wm-0.4.2.tar.xz
SRCCD = archive
BUILD = make
BUILDDIR = xcb-util-wm-0.4.2
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
