COMMENT = Simple X hotkey daemon
VERSION = 0.6.3
REVISION = 0
CATEGORIES = xapps
PKGNAME = sxhkd
HOMEPAGE = https://github.com/baskerville/sxhkd
ARCHIVE = 0.6.3.tar.gz
LINK = https://github.com/baskerville/sxhkd/archive/0.6.3.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = sxhkd-0.6.3
MAKEOPT =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
