COMMENT = C++ bindings for atk
VERSION = 2.28.4
REVISION = 0
CATEGORIES = libs
PKGNAME = atkmm2.28
HOMEPAGE = https://www.gtkmm.org/en/
ARCHIVE = atkmm-2.28.4.tar.xz
LINK = https://download.gnome.org/sources/atkmm/2.28/atkmm-2.28.4.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = atkmm-2.28.4
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
