COMMENT = type-safe Signal Framework for C++
VERSION = 2.12.1
REVISION = 0
CATEGORIES = libs
PKGNAME = libsigc++
HOMEPAGE = https://github.com/libsigcplusplus/libsigcplusplus
ARCHIVE = libsigc++-2.12.1.tar.xz
LINK = https://download.gnome.org/sources/libsigc++/2.12/libsigc++-2.12.1.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = libsigc++-2.12.1
BUILD_OPTION = -Dbuild-documentation=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
