COMMENT = A collection of GSettings schemas
VERSION = 49.1
V = 49
REVISION = 0
CATEGORIES = misc
PKGNAME = gsettings_desktop_schemas
HOMEPAGE = https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas
ARCHIVE = gsettings-desktop-schemas-${VERSION}.tar.xz
LINK = https://download.gnome.org/sources/gsettings-desktop-schemas/${V}/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = gsettings-desktop-schemas-${VERSION}

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
