COMMENT = A fast and light image viewer.
VERSION = 3.11.2
REVISION = 0
CATEGORIES = xapps
PKGNAME = feh
HOMEPAGE = https://feh.finalrewind.org
LINK = ${HOMEPAGE}/feh-${VERSION}.tar.bz2
ARCHIVE = feh-${VERSION}.tar.bz2
SRCCD = archive
BUILD = make
BUILDDIR = feh-${VERSION}
MAKEFLAGS = "curl=1 exif=1 inotify=1 stat64=1 magic=1"

include /usr/share/mk/lfs.port.mk
