COMMENT = Generates status bar for dzen2, xmobar or similar
VERSION = 2.15
REVISION = 0
CATEGORIES = xapps
PKGNAME = i3status
HOMEPAGE = https://i3wm.org/i3status/
LINK = https://i3wm.org/i3status/i3status-2.15.tar.xz
ARCHIVE = i3status-2.15.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = i3status-2.15
BUILD_OPTION = 

include /usr/share/mk/lfs.port.mk
