COMMENT = The typefaces for GNOME
VERSION = 49.0
REVISION = 0
CATEGORIES = misc
PKGNAME = adwaita_fonts
HOMEPAGE = https://gitlab.gnome.org/GNOME/adwaita-fonts
ARCHIVE = adwaita-fonts-49.0.tar.xz
LINK = https://download.gnome.org/sources/adwaita-fonts/49/adwaita-fonts-49.0.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = adwaita-fonts-49.0
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
