COMMENT = Dconf Editor is a viewer and editor of applications internal settings
VERSION = 49.0
REVISION = 0
CATEGORIES = tool
PKGNAME = dconf_editor
HOMEPAGE = https://wiki.gnome.org/Apps/DconfEditor
ARCHIVE = dconf-editor-49.0.tar.xz
LINK = https://download.gnome.org/sources/dconf-editor/49/dconf-editor-49.0.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = dconf-editor-49.0
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
