COMMENT = X11 keyboard file manipulation library
VERSION = 1.1.3
REVISION = 0
CATEGORIES = libs
PKGNAME = libxkbfile
HOMEPAGE = https://xorg.freedesktop.org/
ARCHIVE = libxkbfile-${VERSION}.tar.xz
LINK = https://www.x.org/releases/individual/lib/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = libxkbfile-${VERSION}
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
