COMMENT = Lightweight C++ command line option parser as a header only library
VERSION = 3.3.1
REVISION = 0
CATEGORIES = libs
PKGNAME = cxxopts
HOMEPAGE = https://github.com/jarro2783/cxxopts
ARCHIVE = cxxopts-3.3.1.tar.gz
LINK = https://github.com/jarro2783/cxxopts/archive/v3.3.1/cxxopts-3.3.1.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = cxxopts-3.3.1
BUILD_OPTION = -DBUILD_SHARED_LIBS=ON \
	-DCMAKE_BUILD_TYPE=None \
	-DCXXOPTS_BUILD_TESTS=ON

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
