COMMENT = Create panels and other desktop components in Wayland using the Layer Shell protocol
VERSION = 0.9.2
REVISION = 0
CATEGORIES = libs
PKGNAME = gtk_layer_shell
HOMEPAGE = https://github.com/wmww/gtk-layer-shell
ARCHIVE = v0.9.2.tar.gz
LINK = https://github.com/wmww/gtk-layer-shell/archive/v0.9.2.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = gtk-layer-shell-0.9.2
BUILD_OPTION = -Dexamples=false \
	-Ddocs=false \
	-Dtests=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
