COMMENT = girara - gtk user interface that focuses on simplicity and minimalism
VERSION = 0.4.5
REVISION = 0
CATEGORIES = libs
PKGNAME = girara
HOMEPAGE = https://git.pwmt.org/pwmt/girara
ARCHIVE = 0.4.5.tar.gz
LINK = https://github.com/pwmt/girara/archive/refs/tags/0.4.5.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = girara-0.4.5
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
