COMMENT = Compact xserver to run under wayland for compatibility
VERSION = 24.1.9
REVISION = 0
CATEGORIES = xapps
PKGNAME = xwayland
HOMEPAGE = https://www.x.org/wiki
ARCHIVE = xwayland-24.1.9.tar.xz
LINK = https://xorg.freedesktop.org/archive/individual/xserver/xwayland-24.1.9.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = xwayland-24.1.9
BUILD_OPTION = -Dxvfb=false -Dxdmcp=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
