COMMENT = A MIME database.
VERSION = 2.4
REVISION = 0
CATEGORIES = misc
PKGNAME = shared_mime_info
HOMEPAGE = https://www.freedesktop.org/wiki/Specifications/shared-mime-info-spec/
ARCHIVE = shared-mime-info-2.4.tar.gz
LINK = https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/2.4/shared-mime-info-2.4.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = shared-mime-info-2.4
BUILD_OPTION = -Dupdate-mimedb=true
XML_CATALOG_FILES = /etc/xml/catalog

export XML_CATALOG_FILES

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
