COMMENT = Screen recording for wlroots-based compositors
VERSION = 0.6.0
REVISION = 0
CATEGORIES = wayland
PKGNAME = wf_recorder
HOMEPAGE = https://github.com/ammen99/wf-recorder
ARCHIVE = v0.6.0.tar.gz
LINK = https://github.com/ammen99/wf-recorder/archive/v0.6.0/v0.6.0.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = wf-recorder-0.6.0
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
