COMMENT = A drop-in replacement for the wlroots scene API
VERSION = 0.4.1
REVISION = 0
CATEGORIES = libs
PKGNAME = scenefx
HOMEPAGE = https://github.com/wlrfx/scenefx
ARCHIVE = ${VERSION}.tar.gz
LINK = https://github.com/wlrfx/scenefx/archive/refs/tags/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = scenefx-${VERSION}
BUILD_OPTION = -Dexamples=false

prepare:

post_build:

include /usr/share/mk/lfs.port.mk
